package io.starter.StackGen.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import org.springframework.validation.annotation.Validated;
import javax.validation.Valid;
import javax.validation.constraints.*;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.starter.ignite.model.DataModelObject;
/**
 ############################## DO NOT EDIT: GENERATED FILE ##############################

    Generated by Starter StackGen: http://stackgen.io
    Powered by Swagger Codegen: http://swagger.io
    
	Generator version: (2.4.8)
	
	Template file: JavaSpring/pojo.mustache
	
############################## DO NOT EDIT: GENERATED FILE ##############################
 
 Description: Tag
 */
 


@JsonInclude(JsonInclude.Include.NON_EMPTY)

@javax.annotation.Generated(value = "io.starter.ignite.generator.swagger.languages.StackGenSpringCodegen", date = "2020-06-10T12:46:05.059-07:00")

public class Tag  implements  io.starter.ignite.model.DataModelObject {

  @JsonProperty("id")
  public Long id = null;


  @JsonProperty("name")
  public String name = null;


  @JsonProperty("keyVersion")
  public Long keyVersion = null;


  @JsonProperty("keySpec")
  public String keySpec = "dev";


  @JsonProperty("ownerId")
  public Long ownerId = null;


  @JsonProperty("createdDate")
  public OffsetDateTime createdDate = null;


  @JsonProperty("modifiedDate")
  public OffsetDateTime modifiedDate = null;

   /**
   * Primary Key for Object (generated column)
   * @return id
  **/


  @ApiModelProperty(name="id",       value = "Primary Key for Object (generated column)")
  public Long getId() {
    return id;
  }

  public Tag name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/


  @ApiModelProperty(name="name",       value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Tag keyVersion(Long keyVersion) {
    this.keyVersion = keyVersion;
    return this;
  }

   /**
   * The version of the SecureField key used to crypt this row (generated column)
   * @return keyVersion
  **/


  @ApiModelProperty(name="keyVersion",       value = "The version of the SecureField key used to crypt this row (generated column)")
  public Long getKeyVersion() {
    return keyVersion;
  }

  public void setKeyVersion(Long keyVersion) {
    this.keyVersion = keyVersion;
  }

   /**
   * The spec of the SecureField key used to crypt this row (generated column)
   * @return keySpec
  **/


  @ApiModelProperty(name="keySpec", example = "keySource:system",       value = "The spec of the SecureField key used to crypt this row (generated column)")
  public String getKeySpec() {
    return keySpec;
  }

  public Tag ownerId(Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * The ID of the user that owns this data (generated column)
   * @return ownerId
  **/


  @ApiModelProperty(name="ownerId",       value = "The ID of the user that owns this data (generated column)")
  public Long getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(Long ownerId) {
    this.ownerId = ownerId;
  }

   /**
   * The created date for this record/object (generated column)
   * @return createdDate
  **/

  @Valid

  @ApiModelProperty(name="createdDate",       value = "The created date for this record/object (generated column)")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public Tag modifiedDate(OffsetDateTime modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * The last-modified date for this record/object (generated column)
   * @return modifiedDate
  **/

  @Valid

  @ApiModelProperty(name="modifiedDate",       value = "The last-modified date for this record/object (generated column)")
  public OffsetDateTime getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(OffsetDateTime modifiedDate) {
    this.modifiedDate = modifiedDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tag tag = (Tag) o;
    return Objects.equals(this.id, tag.id) &&
        Objects.equals(this.name, tag.name) &&
        Objects.equals(this.keyVersion, tag.keyVersion) &&
        Objects.equals(this.keySpec, tag.keySpec) &&
        Objects.equals(this.ownerId, tag.ownerId) &&
        Objects.equals(this.createdDate, tag.createdDate) &&
        Objects.equals(this.modifiedDate, tag.modifiedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, keyVersion, keySpec, ownerId, createdDate, modifiedDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tag {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    keyVersion: ").append(toIndentedString(keyVersion)).append("\n");
    sb.append("    keySpec: ").append(toIndentedString(keySpec)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
  * Starter StackGen DataModelObject impl.
  */
  @Override
  public DataModelObject getDelegate() {
    return null; // no delegate here
  }
  
  /**
  * Starter StackGen JSON method
  */
  @Override
  public String toJSON() {
    String ret =  new org.json.JSONObject(this).toString();
    ret = ret.replace("\\\"","\"");
    ret = ret.replace("\"}\"", "\"}");
    return ret;
  }
  
  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

